export class Company{
INITIAL:string;
NAME:string;
TELB:string;
ADDRESS:string;
TELA:string;
VAT:string;
EMAIL:String;
WEBSITE:String;
FBDATE:String;
FEDATE:String;
FBDATE_BS:String;
FEDATE_BS:String;
ISBRANCH:Number;
ID:String;
PhiscalID:string;
BRANCHID:string;
ADDRESS2:string;
POSTALCODE:string;
GSTNO:string;
STATE:string;
ORG_TYPE:string;
PLACE:string;
COMPANYID:string;
BILLFORMATS:string;
BILLUNITS:string;
    }